name: Auto Label Inheritance from Parent Issue

on:
  issues:
    types: [opened]

permissions:
  contents: read
  issues: write

jobs:
  inherit-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Debug GH_TOKEN
        run: |
          if [ -z "$GH_TOKEN" ]; then
            echo "❌ GH_TOKEN is not set"
            exit 1
          fi
          echo "✅ GH_TOKEN is set (length: ${#GH_TOKEN})"
          gh auth status || { echo "❌ GH_TOKEN authentication failed"; exit 1; }
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}

      - name: Get parent issue and inherit labels
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          REPO_NAME: ${{ github.event.repository.name }}
          REPO_OWNER: ${{ github.event.repository.owner.login }}
        run: |
          echo "Fetching internal ID of issue #$ISSUE_NUMBER..."

          GRAPHQL_RESPONSE=$(gh api graphql -f owner="$REPO_OWNER" -f repository="$REPO_NAME" -F number="$ISSUE_NUMBER" -f query='
            query ($owner: String!, $repository: String!, $number: Int!) {
              repository(owner: $owner, name: $repository) {
                issue(number: $number) {
                  id
                }
              }
            }')

          if echo "$GRAPHQL_RESPONSE" | jq -e '.errors' >/dev/null; then
            echo "❌ GraphQL error while fetching issue ID:"
            echo "$GRAPHQL_RESPONSE"
            exit 1
          fi

          ISSUE_ID=$(echo "$GRAPHQL_RESPONSE" | jq -r '.data.repository.issue.id')

          if [ -z "$ISSUE_ID" ]; then
            echo "❌ Failed to get issue ID for #$ISSUE_NUMBER"
            exit 1
          fi

          echo "🔍 Issue node ID: $ISSUE_ID"

          echo "Querying for parent issue using GraphQL..."
          PARENT_JSON=$(gh api graphql \
            -H "GraphQL-Features: sub_issues,issue_types" \
            -f issueId="$ISSUE_ID" \
            -f query='
              query($issueId: ID!) {
                node(id: $issueId) {
                  ... on Issue {
                    parent {
                      number
                      labels(first: 100) {
                        nodes {
                          name
                        }
                      }
                    }
                  }
                }
              }')

          if echo "$PARENT_JSON" | jq -e '.errors' >/dev/null; then
            echo "❌ GraphQL error while fetching parent issue:"
            echo "$PARENT_JSON"
            exit 1
          fi

          echo "$PARENT_JSON" | tee parent.json

          PARENT_NUMBER=$(echo "$PARENT_JSON" | jq -r '.data.node.parent.number')
          if [ "$PARENT_NUMBER" = "null" ] || [ -z "$PARENT_NUMBER" ]; then
            echo "⚠️ No parent issue found. Skipping label inheritance."
            exit 0
          fi

          LABELS=$(echo "$PARENT_JSON" | jq -r '.data.node.parent.labels.nodes[].name' | jq -R . | jq -s .)
          if [ "$LABELS" = "[]" ]; then
            echo "ℹ️ Parent issue has no labels. Nothing to inherit."
            exit 0
          fi

          echo "✅ Inheriting labels from parent issue #$PARENT_NUMBER: $(echo "$LABELS" | jq -r '.[]')"

          echo "Fetching current labels..."
          CURRENT_LABELS=$(gh api -H "Accept: application/vnd.github+json" \
            /repos/${REPO_OWNER}/${REPO_NAME}/issues/${ISSUE_NUMBER} \
            --jq '.labels[].name' | jq -R . | jq -s .)
          MERGED_LABELS=$(echo "$CURRENT_LABELS $LABELS" | jq -s 'flatten | unique')

          echo "Applying labels via REST API..."
          gh api -X POST -H "Accept: application/vnd.github+json" \
            /repos/${REPO_OWNER}/${REPO_NAME}/issues/${ISSUE_NUMBER}/labels \
            -f "labels=$MERGED_LABELS" > response.json
          if [ $? -ne 0 ]; then
            echo "❌ Failed to apply labels"
            cat response.json
            exit 1
          fi

          echo "✅ Labels applied successfully."