name: Auto Label Inheritance from Parent Issue

on:
  issues:
    types: [opened]

permissions:
  contents: read

jobs:
  inherit-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Authenticate GitHub CLI
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: echo "${GH_TOKEN}" | gh auth login --with-token

      - name: Set up environment
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          echo "GH_TOKEN=$GH_TOKEN" >> $GITHUB_ENV

      - name: Get parent issue and inherit labels
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          REPO_NAME: ${{ github.event.repository.name }}
          REPO_OWNER: ${{ github.event.repository.owner.login }}
        run: |
          echo "Fetching internal ID of issue #$ISSUE_NUMBER..."

          ISSUE_ID=$(gh api graphql -f owner="$REPO_OWNER" -f repository="$REPO_NAME" -F number="$ISSUE_NUMBER" -f query='
            query ($owner: String!, $repository: String!, $number: Int!) {
              repository(owner: $owner, name: $repository) {
                issue(number: $number) {
                  id
                }
              }
            }' --jq '.data.repository.issue.id')

          if [ -z "$ISSUE_ID" ]; then
            echo "❌ Failed to get issue ID for #$ISSUE_NUMBER"
            exit 1
          fi

          echo "🔍 Issue node ID: $ISSUE_ID"

          echo "Querying for parent issue using GraphQL preview headers..."
          PARENT_JSON=$(gh api graphql \
            -H "GraphQL-Features: sub_issues,issue_types" \
            -f issueId="$ISSUE_ID" \
            -f query='
              query($issueId: ID!) {
                node(id: $issueId) {
                  ... on Issue {
                    parent {
                      number
                      labels(first: 20) {
                        nodes {
                          name
                        }
                      }
                    }
                  }
                }
              }')

          echo "$PARENT_JSON" | tee parent.json

          PARENT_NUMBER=$(echo "$PARENT_JSON" | jq -r '.data.node.parent.number')
          if [ "$PARENT_NUMBER" = "null" ] || [ -z "$PARENT_NUMBER" ]; then
            echo "⚠️ No parent issue found. Skipping label inheritance."
            exit 0
          fi

          LABELS=$(echo "$PARENT_JSON" | jq -r '.data.node.parent.labels.nodes[].name' | jq -R . | jq -s .)
          if [ "$LABELS" = "[]" ]; then
            echo "ℹ️ Parent issue has no labels. Nothing to inherit."
            exit 0
          fi

          echo "✅ Inheriting labels from parent issue #$PARENT_NUMBER: $LABELS"

          curl -X POST -H "Authorization: token $GH_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/${REPO_OWNER}/${REPO_NAME}/issues/${ISSUE_NUMBER}/labels \
            -d "{\"labels\": $LABELS}"